<?php
$catId = $_GET['id'] ?? '';
$cat = findCat($catId, $cats);
if (!$cat) { echo "<div class='alert alert-warning'>Кошка не найдена</div>"; return; }
$cat_tasks = array_filter($tasks, fn($t) => $t['cat_id'] == $cat['id']);
$ph = getCatMainPhoto($cat); $st = $cat['status_history']['current'];
$cat_finances = array_filter($finances, fn($f) => $f['cat_id'] === $cat['id']);
$cat_income = array_sum(array_map(fn($f) => $f['type'] === 'income' ? $f['amount'] : 0, $cat_finances));
$cat_expense = array_sum(array_map(fn($f) => $f['type'] === 'expense' ? $f['amount'] : 0, $cat_finances));
$cat_balance = $cat_income - $cat_expense;
?>
<div class="no-print"><a href="?action=cats" class="btn btn-outline-secondary mb-3 md-btn"><span class="material-icons align-middle me-1" style="font-size:18px">arrow_back</span> Назад</a></div>
<div class="md-card p-4 mb-4"><div class="row align-items-center"><div class="col-auto"><div class="md-avatar" style="width:110px;height:110px;font-size:2.5rem"><?= $ph?"<img src='".escape($ph['path'])."' alt='avatar'>":"<span class='material-icons'>pets</span>" ?></div></div>
<div class="col"><h2 class="mb-1 fw-bold"><?= escape($cat['identification']['name']) ?></h2>
<div class="d-flex flex-wrap gap-2 mb-3"><span class="md-badge md-badge-<?= $st==='adopted'?'adopted':($st==='ready_for_adoption'?'ready':($st==='treatment'?'treatment':'caught')) ?>"><?= CAT_STATUS_LABELS[$st] ?></span><span class="info-chip">ID: <?= $cat['id'] ?></span><?= $cat['medical']['sterilization']['done']?'<span class="info-chip bg-success bg-opacity-10 text-success">✂️ Стерил.</span>':'' ?></div>
<div class="row g-2 small text-muted"><div class="col-auto"><span class="material-icons align-middle" style="font-size:16px">transgender</span> <?= $cat['identification']['sex']==='male'?'Кот':($cat['identification']['sex']==='female'?'Кошка':'—') ?></div>
<div class="col-auto"><span class="material-icons align-middle" style="font-size:16px">cake</span> <?= escape($cat['identification']['approx_age']?:'—') ?></div><div class="col-auto"><span class="material-icons align-middle" style="font-size:16px">color_lens</span> <?= escape($cat['identification']['color']?:'—') ?></div>
<div class="col-auto"><span class="material-icons align-middle" style="font-size:16px">place</span> <?= escape($cat['identification']['location']?:'—') ?></div></div></div></div></div>

<ul class="nav nav-tabs md-tabs mb-4 no-print">
    <?php foreach(['ident'=>'📋 Данные','photos'=>'📷 Фото','status'=>'🔄 Статус','med'=>'💉 Медицина','beh'=>'🧠 Характер','cont'=>'📞 Контакты','notes'=>'📝 Дневник','adopt'=>'🏡 Пристройство','finance'=>'💰 Финансы','print'=>'🖨️ Печать'] as $k=>$v): ?>
    <li class="nav-item"><a class="nav-link <?= $k==='ident'?'active':'' ?>" data-bs-toggle="tab" href="#t_<?= $k ?>"><?= $v ?></a></li><?php endforeach; ?>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="t_ident"><div class="md-card p-4"><form method="POST" action="?action=update_cat_ident" class="row g-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>">
        <?php foreach(['name'=>'Кличка','color'=>'Окрас','approx_age'=>'Возраст','breed'=>'Порода','marks'=>'Приметы','description'=>'Описание','intake_date'=>'Дата поступления','location'=>'Место','microchip'=>'Микрочип'] as $k=>$v): ?>
        <div class="col-md-6"><label class="form-label small fw-medium"><?= $v ?></label><input type="text" name="<?= $k ?>" class="form-control md-field" value="<?= escape($cat['identification'][$k]) ?>"></div><?php endforeach; ?>
        <div class="col-md-3"><label class="form-label small fw-medium">Пол</label><select name="sex" class="form-select md-field"><?php foreach(['male'=>'Кот','female'=>'Кошка','unknown'=>'Неизвестно'] as $k=>$v): ?><option value="<?= $k ?>" <?= $cat['identification']['sex']==$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div>
        <div class="col-md-3"><label class="form-label small fw-medium">Группа</label><select name="age_group" class="form-select md-field"><?php foreach(['kitten'=>'Котёнок','young'=>'Молодое','adult'=>'Взрослое','senior'=>'Пожилое','unknown'=>'Не определена'] as $k=>$v): ?><option value="<?= $k ?>" <?= $cat['identification']['age_group']==$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div>
        <div class="col-12 mt-2"><button class="btn btn-primary md-btn px-4">💾 Сохранить</button></div></form></div></div>

    <div class="tab-pane fade" id="t_photos"><div class="md-card p-4 mb-3"><form method="POST" action="?action=add_cat_photo" enctype="multipart/form-data"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>">
        <div class="row g-2 align-items-end"><div class="col-md-5"><input type="file" name="photo" class="form-control md-field" required></div><div class="col-md-4"><input type="text" name="caption" class="form-control md-field" placeholder="Подпись"></div><div class="col-md-2"><div class="form-check mt-2"><input type="checkbox" name="is_main" id="mainPh" class="form-check-input"><label class="form-label mb-0" for="mainPh">Главное фото</label></div></div><div class="col-md-1"><button class="btn btn-success w-100 md-btn">⬆️</button></div></div></form></div>
        <div class="row g-3"><?php if(!empty($cat['photos'])): foreach($cat['photos'] as $p): ?><div class="col-md-3 col-lg-2"><div class="md-card overflow-hidden position-relative"><img src="<?= escape($p['path']) ?>" class="w-100" style="height:160px;object-fit:cover" alt="<?= escape($p['caption']) ?>"><div class="p-2 small bg-light"><?= escape($p['caption']) ?> <?= $p['is_main']?'⭐':'' ?></div></div></div><?php endforeach; else: ?><div class="col-12 text-center py-5 text-muted">Нет фото</div><?php endif; ?></div></div>

    <div class="tab-pane fade" id="t_status"><div class="md-card p-4 mb-3"><form method="POST" action="?action=update_cat_status"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>"><div class="row align-items-end g-3">
        <div class="col-md-4"><label class="form-label small fw-medium">Статус</label><select name="new_status" class="form-select md-field"><?php foreach(CAT_STATUS_LABELS as $k=>$v): ?><option value="<?= $k ?>" <?= $cat['status_history']['current']==$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div>
        <div class="col"><label class="form-label small fw-medium">Комментарий</label><input type="text" name="comment" class="form-control md-field" placeholder="Причина"></div><div class="col-auto"><button class="btn btn-warning md-btn px-4">Обновить</button></div></div></form></div>
        <h5 class="fw-bold mb-3">📜 История</h5><div class="md-card p-0 overflow-hidden"><ul class="list-group list-group-flush">
        <?php foreach(array_reverse($cat['status_history']['log']) as $h): $u=findUser($h['user_id'],$users); ?><li class="list-group-item d-flex justify-content-between align-items-center py-3"><div><strong class="text-primary"><?= CAT_STATUS_LABELS[$h['status']] ?></strong> <span class="text-muted">— <?= escape($h['comment']) ?></span></div><div class="text-end small"><span class="badge bg-light text-dark border"><?= escape($u['name']?:'Система') ?></span><br><span class="text-muted"><?= $h['date'] ?></span></div></li><?php endforeach; ?></ul></div></div>

    <div class="tab-pane fade" id="t_med"><div class="row g-3"><div class="col-md-6">
        <div class="md-card p-3 mb-3"><h6 class="fw-bold mb-2">✂️ Стерилизация</h6><form method="POST" action="?action=update_cat_sterilization"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>"><div class="form-check mb-2"><input type="checkbox" name="done" id="ster" <?= $cat['medical']['sterilization']['done']?'checked':'' ?>><label for="ster">Проведена</label></div><input type="date" name="date" class="form-control md-field mb-2" value="<?= escape($cat['medical']['sterilization']['date']) ?>"><input type="text" name="notes" class="form-control md-field mb-2" placeholder="Примечания" value="<?= escape($cat['medical']['sterilization']['notes']) ?>"><button class="btn btn-sm btn-primary md-btn">Сохранить</button></form></div>
        <h6 class="fw-bold mb-2">💊 Лекарства</h6><form method="POST" action="?action=add_cat_med" class="md-card p-3 mb-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>"><input type="text" name="drug" class="form-control md-field mb-1" placeholder="Препарат"><input type="text" name="dosage" class="form-control md-field mb-2" placeholder="Дозировка"><div class="row g-1 mb-2"><div class="col"><input type="date" name="start" class="form-control md-field"></div><div class="col"><input type="date" name="end" class="form-control md-field"></div></div><button class="btn btn-sm btn-success md-btn w-100">+ Курс</button></form>
        <ul class="list-group mb-3"><?php if(empty($cat['medical']['current_meds'])) echo "<li class='list-group-item small text-muted'>Нет</li>"; foreach($cat['medical']['current_meds'] as $m): ?><li class="list-group-item small border-start border-4 border-success">💊 <?= escape($m['drug']) ?> (<?= escape($m['dosage']) ?>)<br><?= escape($m['start']) ?> → <?= escape($m['end']) ?></li><?php endforeach; ?></ul>
    </div><div class="col-md-6"><h6 class="fw-bold mb-2">🩺 Процедуры</h6><form method="POST" action="?action=add_cat_procedure" class="md-card p-3 mb-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>"><select name="type" class="form-select md-field mb-2"><option>Вакцинация</option><option>Дегельминтизация</option><option>Обработка</option></select><input type="text" name="drug_name" class="form-control md-field mb-2" placeholder="Препарат"><div class="row g-1 mb-2"><div class="col"><input type="date" name="date" class="form-control md-field"></div><div class="col"><input type="text" name="clinic" class="form-control md-field" placeholder="Клиника"></div></div><textarea name="notes" class="form-control md-field mb-2" rows="1"></textarea><button class="btn btn-sm btn-primary md-btn w-100">Добавить</button></form>
    <ul class="list-group"><?php if(empty($cat['medical']['procedures'])) echo "<li class='list-group-item small text-muted'>Нет</li>"; foreach($cat['medical']['procedures'] as $p): ?><li class="list-group-item small border-start border-4 border-info">🩺 <?= escape($p['type']) ?>: <?= escape($p['name']) ?> (<?= escape($p['date']) ?>) <?= escape($p['clinic']) ?></li><?php endforeach; ?></ul></div></div></div>

    <div class="tab-pane fade" id="t_beh"><form method="POST" action="?action=update_cat_behavior" class="md-card p-4"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>">
    <?php foreach(['people_relation'=>'👥 Люди','animals_relation'=>'🐾 Животные','litter_box'=>'🚽 Лоток','independence'=>'⚡ Активность','special_needs'=>'🍲 Диета'] as $k=>$v): ?><label class="form-label small fw-medium"><?= $v ?></label><textarea name="<?= $k ?>" class="form-control md-field mb-3" rows="2"><?= escape($cat['behavior'][$k]) ?></textarea><?php endforeach; ?><button class="btn btn-primary md-btn px-4">💾 Сохранить</button></form></div>

    <div class="tab-pane fade" id="t_cont"><form method="POST" action="?action=update_cat_contacts" class="md-card p-4 row g-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>">
    <div class="col-md-3"><label class="form-label small fw-medium">Куратор ID</label><input type="number" name="curator_id" class="form-control md-field" value="<?= $cat['contacts']['curator_user_id'] ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Имя куратора</label><input type="text" name="curator_name" class="form-control md-field" value="<?= escape($cat['contacts']['curator_name']) ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Телефон</label><input type="text" name="curator_phone" class="form-control md-field" value="<?= escape($cat['contacts']['curator_phone']) ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Email</label><input type="email" name="curator_email" class="form-control md-field" value="<?= escape($cat['contacts']['curator_email']) ?>"></div>
    <div class="col-12"><hr class="my-1"></div>
    <div class="col-md-6"><label class="form-label small fw-medium">Ловец</label><input type="text" name="finder_name" class="form-control md-field" value="<?= escape($cat['contacts']['finder_name']) ?>"></div>
    <div class="col-md-6"><label class="form-label small fw-medium">Контакты</label><input type="text" name="finder_contacts" class="form-control md-field" value="<?= escape($cat['contacts']['finder_contacts']) ?>"></div>
    <div class="col-12 mt-2"><button class="btn btn-primary md-btn px-4">💾 Сохранить</button></div></form></div>

    <div class="tab-pane fade" id="t_notes"><form method="POST" action="?action=add_cat_note" class="md-card p-3 mb-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>"><div class="d-flex gap-2"><textarea name="text" class="form-control md-field" rows="2" placeholder="Наблюдение..." required></textarea><button class="btn btn-primary align-self-end md-btn px-3">Записать</button></div></form>
    <ul class="list-group"><?php if(empty($cat['notes'])) echo "<li class='list-group-item text-muted'>Нет записей</li>"; foreach(array_reverse($cat['notes']) as $n): $u=findUser($n['user_id'],$users); ?><li class="list-group-item py-3"><div class="d-flex justify-content-between mb-1"><strong><?= escape($u['name']?:'Пользователь') ?></strong> <small class="text-muted"><?= $n['date'] ?></small></div><?= nl2br(escape($n['text'])) ?></li><?php endforeach; ?></ul></div>

    <div class="tab-pane fade" id="t_adopt"><form method="POST" action="?action=update_adoption" class="md-card p-4 row g-3"><input type="hidden" name="cat_id" value="<?= $cat['id'] ?>">
    <div class="col-md-4"><label class="form-label small fw-medium">Статус</label><select name="status" class="form-select md-field"><?php foreach(ADOPT_STATUSES as $k=>$v): ?><option value="<?= $k ?>" <?= $cat['adoption']['status']==$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label small fw-medium">Имя владельца</label><input type="text" name="owner_name" class="form-control md-field" value="<?= escape($cat['adoption']['owner_name']) ?>"></div>
    <div class="col-md-4"><label class="form-label small fw-medium">Контакты</label><input type="text" name="owner_contacts" class="form-control md-field" value="<?= escape($cat['adoption']['owner_contacts']) ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Проверка дома</label><input type="date" name="hc_date" class="form-control md-field" value="<?= $cat['adoption']['homecheck_date'] ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Результат</label><input type="text" name="hc_result" class="form-control md-field" value="<?= escape($cat['adoption']['homecheck_result']) ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Дата договора</label><input type="date" name="contract" class="form-control md-field" value="<?= $cat['adoption']['contract_date'] ?>"></div>
    <div class="col-md-3"><label class="form-label small fw-medium">Дата передачи</label><input type="date" name="transfer" class="form-control md-field" value="<?= $cat['adoption']['transfer_date'] ?>"></div>
    <div class="col-12 mt-2"><button class="btn btn-primary md-btn px-4">💾 Обновить</button></div></form></div>

    <div class="tab-pane fade" id="t_finance">
    <div class="row g-4 mb-4"><div class="col-md-4"><div class="md-card p-3 text-center border-start border-4 border-success"><h6 class="text-muted small fw-bold">Доходы</h6><h3 class="finance-income mb-0"><?= number_format($cat_income, 2, '.', ' ') ?> ₽</h3></div></div><div class="col-md-4"><div class="md-card p-3 text-center border-start border-4 border-danger"><h6 class="text-muted small fw-bold">Расходы</h6><h3 class="finance-expense mb-0"><?= number_format($cat_expense, 2, '.', ' ') ?> ₽</h3></div></div><div class="col-md-4"><div class="md-card p-3 text-center border-start border-4 <?= $cat_balance>=0?'border-success':'border-danger' ?>"><h6 class="text-muted small fw-bold">Баланс</h6><h3 class="<?= $cat_balance>=0?'finance-balance-positive':'finance-balance-negative' ?> mb-0"><?= number_format($cat_balance, 2, '.', ' ') ?> ₽</h3></div></div></div>
    <div class="md-card p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="fw-bold mb-0">История операций</h5><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addFinanceModal" data-cat-id="<?= $cat['id'] ?>" data-cat-name="<?= escape($cat['identification']['name']) ?>"><span class="material-icons" style="font-size:18px">add</span> Добавить</button></div>
    <?php if(empty($cat_finances)): ?><p class="text-muted text-center py-4">Нет записей</p><?php else: ?><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Дата</th><th>Тип</th><th>Категория</th><th>Сумма</th><th>Описание</th><th>Действия</th></tr></thead><tbody>
    <?php usort($cat_finances,fn($a,$b)=>strcmp($b['date'],$a['date'])); foreach($cat_finances as $f): $tl=FINANCE_TYPES[$f['type']][$f['category']]??$f['category']; ?>
    <tr><td><?= escape($f['date']) ?></td><td><?= $f['type']==='income'?'<span class="badge bg-success bg-opacity-10 text-success">Доход</span>':'<span class="badge bg-danger bg-opacity-10 text-danger">Расход</span>' ?></td><td><?= escape($tl) ?></td><td class="<?= $f['type']==='income'?'finance-income':'finance-expense' ?>"><?= number_format($f['amount'],2,'.',' ') ?> ₽</td><td><?= escape($f['description']) ?></td>
    <td><form method="POST" action="?action=delete_finance" class="d-inline" onsubmit="return confirm('Удалить?')"><input type="hidden" name="finance_id" value="<?= $f['id'] ?>"><button class="btn btn-sm btn-outline-danger"><span class="material-icons" style="font-size:18px">delete</span></button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>

    <div class="tab-pane fade" id="t_print"><div class="md-card p-5 border-0 shadow-none">
        <div class="text-center mb-4"><h2 class="fw-bold">Карточка животного</h2><h4 class="text-primary"><?= escape($cat['identification']['name']) ?></h4><?= $ph?"<img src='".escape($ph['path'])."' style='max-height:250px;border-radius:8px;margin:15px 0' alt='Фото'>":"" ?></div>
        <div class="row g-4 mb-4"><div class="col-md-6"><h5 class="border-bottom pb-2 mb-3">Основная информация</h5><p><strong>ID:</strong> <?= $cat['id'] ?></p><p><strong>Пол:</strong> <?= $cat['identification']['sex']==='male'?'Кот':($cat['identification']['sex']==='female'?'Кошка':'Неизвестно') ?></p><p><strong>Возраст:</strong> <?= escape($cat['identification']['approx_age']?:'Не указан') ?></p><p><strong>Окрас:</strong> <?= escape($cat['identification']['color']) ?></p></div><div class="col-md-6"><h5 class="border-bottom pb-2 mb-3">Медицина</h5><p><strong>Стерилизация:</strong> <?= $cat['medical']['sterilization']['done']?'Да':'Нет' ?></p><p><strong>Лечение:</strong> <?= empty($cat['medical']['current_meds'])?'Нет':'Да' ?></p></div></div>
        <div class="mt-4 pt-3 border-top text-center text-muted small"><p>Сгенерировано <?= date('d.m.Y H:i') ?></p></div>
    </div><div class="no-print mt-3 text-center"><button onclick="window.print()" class="btn btn-primary btn-lg md-btn"><span class="material-icons align-middle me-2">print</span> Распечатать</button></div></div>
</div>

<h4 class="mt-4 fw-bold mb-3 no-print">📌 Задачи по кошке</h4>
<?php if($cat_tasks): ?><div class="md-card p-2 overflow-hidden no-print"><table class="table table-sm align-middle mb-0"><thead><tr><th>Тип</th><th>Название</th><th>Статус</th><th>Исполнитель</th><th class="text-end">Действие</th></tr></thead><tbody>
    <?php foreach($cat_tasks as $t): $u=findUser($t['assignee_id'],$users); $c=$t['status']=='done'?'success':'secondary'; ?>
    <tr><td><?= TASK_TYPES[$t['type']] ?></td><td><?= escape($t['title']) ?></td><td><span class="md-badge bg-<?= $c ?> bg-opacity-25 text-<?= $c ?>"><?= STATUS_LABELS[$t['status']] ?></span></td><td><?= escape($u['name']) ?></td><td class="text-end"><form method="POST" action="?action=update_task" class="d-inline"><input type="hidden" name="task_id" value="<?= $t['id'] ?>"><select name="status" class="form-select form-select-sm md-field" style="width:130px" onchange="this.form.submit()"><?php foreach(STATUS_LABELS as $k=>$v): ?><option value="<?= $k ?>" <?= $t['status']==$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></form></td></tr>
    <?php endforeach; ?></tbody></table></div><?php else: echo "<div class='md-card p-4 text-center text-muted no-print'>Нет задач</div>"; endif; ?>