<?php $finance_stats = getFinanceStats($finances, $cats); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><h3 class="fw-bold m-0">💰 Финансы</h3><button class="btn btn-primary md-btn d-flex align-items-center gap-1" data-bs-toggle="modal" data-bs-target="#addFinanceModal"><span class="material-icons">add_circle</span> Добавить</button></div>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="md-card p-3 text-center h-100 border-start border-4 border-success"><h6 class="text-muted text-uppercase small fw-bold">Доходы</h6><h2 class="finance-income mb-0"><?= number_format($finance_stats['total_income'], 2, '.', ' ') ?> ₽</h2></div></div><div class="col-md-4"><div class="md-card p-3 text-center h-100 border-start border-4 border-danger"><h6 class="text-muted text-uppercase small fw-bold">Расходы</h6><h2 class="finance-expense mb-0"><?= number_format($finance_stats['total_expense'], 2, '.', ' ') ?> ₽</h2></div></div><div class="col-md-4"><div class="md-card p-3 text-center h-100 border-start border-4 <?= $finance_stats['balance']>=0?'border-success':'border-danger' ?>"><h6 class="text-muted text-uppercase small fw-bold">Баланс</h6><h2 class="<?= $finance_stats['balance']>=0?'finance-balance-positive':'finance-balance-negative' ?> mb-0"><?= number_format($finance_stats['balance'], 2, '.', ' ') ?> ₽</h2></div></div></div>

<div class="md-card p-4 mb-4"><h5 class="fw-bold mb-3">🐱 Расходы по кошкам</h5><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Кошка</th><th>Доходы</th><th>Расходы</th><th>Баланс</th><th>Действия</th></tr></thead><tbody>
<?php foreach($finance_stats['by_cat'] as $cid=>$d): $cb=$d['income']-$d['expense']; ?>
<tr><td><?= escape($d['name']) ?></td><td class="finance-income"><?= number_format($d['income'],2,'.',' ') ?> ₽</td><td class="finance-expense"><?= number_format($d['expense'],2,'.',' ') ?> ₽</td><td class="<?= $cb>=0?'finance-balance-positive':'finance-balance-negative' ?>"><?= number_format($cb,2,'.',' ') ?> ₽</td><td><a href="?action=cat&id=<?= $cid ?>#t_finance" class="btn btn-sm btn-outline-primary">Подробнее</a></td></tr>
<?php endforeach; ?></tbody></table></div></div>

<div class="md-card p-4"><h5 class="fw-bold mb-3">📋 История</h5><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Дата</th><th>Тип</th><th>Категория</th><th>Кошка</th><th>Сумма</th><th>Описание</th><th>Действия</th></tr></thead><tbody>
<?php usort($finances,fn($a,$b)=>strcmp($b['date'],$a['date'])); foreach(array_slice($finances,0,50) as $f): $c=findCat($f['cat_id'],$cats); $tl=FINANCE_TYPES[$f['type']][$f['category']]??$f['category']; ?>
<tr><td><?= escape($f['date']) ?></td><td><?= $f['type']==='income'?'<span class="badge bg-success bg-opacity-10 text-success">Доход</span>':'<span class="badge bg-danger bg-opacity-10 text-danger">Расход</span>' ?></td><td><?= escape($tl) ?></td><td><?= $c?escape($c['identification']['name']):'<span class="text-muted">Общие</span>' ?></td><td class="<?= $f['type']==='income'?'finance-income':'finance-expense' ?>"><?= number_format($f['amount'],2,'.',' ') ?> ₽</td><td><?= escape($f['description']) ?></td>
<td><form method="POST" action="?action=delete_finance" class="d-inline" onsubmit="return confirm('Удалить?')"><input type="hidden" name="finance_id" value="<?= $f['id'] ?>"><button class="btn btn-sm btn-outline-danger"><span class="material-icons" style="font-size:18px">delete</span></button></form></td></tr>
<?php endforeach; ?></tbody></table></div></div>